id: P009370
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:35:37.102122
source_metadata:
  id: bdr:W14457
  title: དགའ་ལྡན་ཤར་རྩེའི་ཆོས་འབྱུང
  author: ''
  volumes:
    dc7e463dfa3142948a7abfecf12a7524:
      image_group_id: I1KG2162
      title: ''
      volume_number: 1
      total_pages: 286
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
